# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_files/signup_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signupDialog(object):
    def setupUi(self, signupDialog):
        signupDialog.setObjectName("signupDialog")
        signupDialog.resize(598, 240)
        self.gridLayout = QtWidgets.QGridLayout(signupDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.windowTitle = QtWidgets.QLabel(signupDialog)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(19)
        self.windowTitle.setFont(font)
        self.windowTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.windowTitle.setObjectName("windowTitle")
        self.verticalLayout.addWidget(self.windowTitle)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(signupDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameFill = QtWidgets.QLineEdit(signupDialog)
        self.nameFill.setObjectName("nameFill")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nameFill)
        self.usernameLabel = QtWidgets.QLabel(signupDialog)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameFill = QtWidgets.QLineEdit(signupDialog)
        self.usernameFill.setObjectName("usernameFill")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.usernameFill)
        self.passwordLabel = QtWidgets.QLabel(signupDialog)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordFill = QtWidgets.QLineEdit(signupDialog)
        self.passwordFill.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordFill.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordFill.setObjectName("passwordFill")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordFill)
        self.buttonBox = QtWidgets.QDialogButtonBox(signupDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.buttonBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.verticalLayout.addLayout(self.formLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(signupDialog)
        self.buttonBox.rejected.connect(signupDialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(signupDialog)

    def retranslateUi(self, signupDialog):
        _translate = QtCore.QCoreApplication.translate
        signupDialog.setWindowTitle(_translate("signupDialog", "Dialog"))
        self.windowTitle.setText(_translate("signupDialog", "Hey! Let\'s create your account!"))
        self.nameLabel.setText(_translate("signupDialog", "Name:"))
        self.usernameLabel.setText(_translate("signupDialog", "Username:"))
        self.passwordLabel.setText(_translate("signupDialog", "Password:"))
